Use qualified container image names in Dockerfile
After we bumped to use the golang:1.20 image content provider job fails
with.

```
Error: creating build container: short-name resolution enforced but cannot prompt without a TTY
```